from core.widgets import (
    ActionsWidget,
    AnnouncementWidget,
    ChartWidget,
    MetricsWidget,
    ResourceListWidget,
    TableWidget,
    TextWidget,
)


DASHBOARD_REGISTRY = {
    "faction": [
        {
            "key": "leader_snapshot",
            "widget": MetricsWidget,
            "title": "Snapshot",
            "options_provider": "get_leader_metrics_widget",
            "priority": 0,
            "width": 12,
        },
        {
            "key": "faction_overview",
            "widget": TableWidget,
            "title": "Faction Overview",
            "options_provider": "get_faction_overview_widget",
            "priority": 1,
            "width": 12,
        },
        {
            "key": "leader_reports",
            "widget": ChartWidget,
            "title": "Enrollment Reports",
            "options_provider": "get_leader_chart_widget",
            "condition": "is_leader_admin",
            "priority": 3,
            "width": 6,
        },
        {
            "key": "leader_actions",
            "widget": ActionsWidget,
            "title": "Quick Actions",
            "options_provider": "get_leader_actions_widget",
            "condition": "is_leader_standard",
            "priority": 8,
            "width": 4,
        },
        {
            "key": "leader_resources",
            "widget": ResourceListWidget,
            "title": "Leadership Resources",
            "options_provider": "get_leader_resources_widget",
            "priority": 9,
            "width": 8,
        },
    ],
    "attendee": [
        {
            "key": "attendee_schedule",
            "widget": TableWidget,
            "title": "Class Schedule",
            "options_provider": "get_attendee_schedule_widget",
            "priority": 1,
            "width": 12,
        },
        {
            "key": "attendee_announcements",
            "widget": AnnouncementWidget,
            "title": "Announcements",
            "options_provider": "get_attendee_announcements_widget",
            "priority": 5,
            "width": 6,
        },
        {
            "key": "attendee_resources",
            "widget": ResourceListWidget,
            "title": "Recommended Resources",
            "options_provider": "get_attendee_resources_widget",
            "priority": 6,
            "width": 6,
        },
    ],
    "faculty": [
        {
            "key": "faculty_schedule",
            "widget": TableWidget,
            "title": "Class Schedule",
            "options_provider": "get_faculty_schedule_widget",
            "priority": 1,
            "width": 12,
        },
        {
            "key": "faculty_resources",
            "widget": ResourceListWidget,
            "title": "Resources",
            "options_provider": "get_faculty_resources_widget",
            "priority": 6,
            "width": 6,
        },
        {
            "key": "faculty_management",
            "widget": TableWidget,
            "title": "Manage Faculty",
            "options_provider": "get_faculty_management_widget",
            "condition": "is_faculty_admin",
            "priority": 8,
            "width": 6,
        },
        {
            "key": "faculty_reports",
            "widget": TableWidget,
            "title": "Recent Reports",
            "options_provider": "get_faculty_reports_widget",
            "condition": "is_faculty_admin",
            "priority": 9,
            "width": 6,
        },
    ],
    "facility": [
        {
            "key": "facility_snapshot",
            "widget": MetricsWidget,
            "title": "Facility Snapshot",
            "options_provider": "get_facility_metrics_widget",
            "priority": 0,
            "width": 12,
        },
        {
            "key": "facility_overview",
            "widget": TextWidget,
            "title": "Overview",
            "options_provider": "get_facility_overview_widget",
            "priority": 1,
            "width": 12,
        },
    ],
    "admin": [
        {
            "key": "admin_actions",
            "widget": ActionsWidget,
            "title": "Admin Shortcuts",
            "options_provider": "get_admin_actions_widget",
            "priority": 0,
            "width": 6,
        },
        {
            "key": "admin_resources",
            "widget": ResourceListWidget,
            "title": "Admin Resources",
            "options_provider": "get_admin_resources_widget",
            "priority": 1,
            "width": 6,
        },
    ],
}
